"""
CLI Detect Command
==================

This module defines the CLI command to run AI text detection on a file.
"""

from pathlib import Path
import sys
import click
import httpx


@click.command(name="detect")
@click.argument("file_path", type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.option(
    "--url",
    type=str,
    default="http://127.0.0.1:8000/api/v1/aidetect/",
    help="The URL of the aidetect service endpoint.",
)
def detect_cmd(file_path: Path, url: str) -> None:
    """
    Detect if the text in a file is AI-generated by sending it to the aidetect service.
    """
    try:
        # Read file contents
        content = file_path.read_text(encoding="utf-8")

        click.echo(f"Sending {file_path} to aidetect service at {url}...")

        # Detect Content-Type using mime magic and/or file extension
        content_type = None
        try:
            import magic

            content_type = magic.from_file(str(file_path), mime=True)
        except (ImportError, Exception):
            pass

        if not content_type:
            import mimetypes

            mimetypes.add_type("text/markdown", ".md")
            mimetypes.add_type("text/markdown", ".markdown")
            content_type, _ = mimetypes.guess_type(str(file_path))

        if not content_type:
            content_type = "text/plain"

        # Send post request to aidetect service with raw body content and Content-Type header
        r = httpx.post(
            url,
            content=content,
            headers={"Content-Type": content_type},
            timeout=15.0,
        )

        if r.status_code == 200:
            result = r.json()
            click.echo(f"Result for {file_path.name}:")
            click.echo(f"  AI-Generated: {result['is_ai']}")
            click.echo(f"  Votes: {result['ai_votes']}/{result['total_models']}")
            if "final_score" in result:
                click.echo(f"  Final Score: {result['final_score']:.4f}")
            if "final_confidence" in result:
                click.echo(f"  Final Confidence: {result['final_confidence']:.4f}")
            click.echo("  Predictions:")
            for name, score in result["predictions"].items():
                model_confidence = result.get("confidences", {}).get(name)
                if model_confidence is None:
                    click.echo(f"    - {name}: {score:.4f}")
                else:
                    click.echo(f"    - {name}: {score:.4f} (confidence: {model_confidence:.4f})")
        else:
            click.echo(f"Error from service (status {r.status_code}): {r.text}", err=True)
            sys.exit(1)

    except Exception as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)
